import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import DataContextProvider from '../context/dataContext'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans bg-main-background bg-no-repeat bg-fixed`}>
        <DataContextProvider>
          <Header />
          {children}
        </DataContextProvider>
      </body>
    </html>
  )
}
